version: "3.9"
services:
  database:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_DB=postit
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8032:5432"
